### PR TITLE
Task/58

### LINKED ISSUE #58: Use refresh token to automatically renew auth token upon expiration
Currently, the access/auth token expires after 1 hour, which causes authentication to fail unless the user signs in again. However, we are already receiving a refresh token during authentication. This can be used to renew the access token automatically without requiring user interaction.

### PR DESCRIPTION
**Pull request by Hirdiyansh**
Closes #58

### CODE REVIEW

File: src/middleware.ts [hunk 1]
```diff
@@ -1,20 +1,50 @@
...
-    const callBackURL = new URL("/auth-callback", request.nextUrl.origin);
+  if (!accessToken && !refreshToken) {
+    console.log("1");
+    const callBackURL = new URL("/signIn", request.nextUrl.origin);
     return NextResponse.redirect(callBackURL);
   }
 
-  return NextResponse.next();
+  if (!accessToken && refreshToken) {
+    console.log("2");
```
Comment (dushyantpant5) [inline src/middleware.ts:23]: Remove this

File: src/middleware.ts [hunk 2]
```diff
@@ -1,20 +1,50 @@
...
 export async function middleware(request: NextRequest) {
   console.log("Middleware triggered for protected route");
 
   const accessToken = await getAccessToken();
+  const refreshToken = await getRefreshToken();
 
-  if (!accessToken || !(await verifyToken(accessToken))) {
-    const callBackURL = new URL("/auth-callback", request.nextUrl.origin);
+  if (!accessToken && !refreshToken) {
+    console.log("1");
```
Comment (dushyantpant5) [inline src/middleware.ts:17]: Remove this

**Review by dushyantpant5 — CHANGES_REQUESTED** [review]

**Review by dushyantpant5 — APPROVED** [review]
LGTM
